#! /usr/bin/env bash

##
# Author : Ben Blazak
# Date   : 2014-01-26
#
# This is a shell script to run the executable generated by typing
# "./generate-files.sh" into the terminal (specifically, the test.exe file),
# and to print out its return value.
#
# Notes:
# - Every line not ending with a backslash ("\") is a separate command.
#   Commands may also be separated by a semicolon (";").  In C++, all commands
#   (or statements, rather) must end with a semicolon.
# - "echo" is a program that prints whatever you pass it (in this case,
#   strings, surrounded by double quotation marks) to stdout (i.e. the terminal)
# - Variables in bash (the scripting language this file is written in) are
#   preceded by a dollar sign, as in "$return_value".  This is not true in C++
#   or C, though it is true in some other languages like Perl and PHP.
# - See the note at the top of "clean.sh" if you're interested in learning more
#   about bash shell scripting.
#

echo "--- running test.exe -------------------------------------"
./test.exe
return_value=$?
echo "----------------------------------------------------------"
echo " The return value of test.exe was: $return_value"
echo " The shell command used to run the program was: ./test.exe"
echo "----------------------------------------------------------"

